const actionTypes = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
  SET_STORES: "SET_STORES",
  SET_CURRENT_STORE: "SET_CURRENT_STORE",
  SET_STORES_WITH_PRODUCT: "SET_STORES_WITH_PRODUCT",
  SET_USER: "SET_USER",
  SET_POOLS: "SET_POOLS"
};

export default actionTypes;
