const actionTypes = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT"
};

export default actionTypes;
